### ISSUE TITLE
Crash in fragment use - open another fragment and coming back to original with TapBarMenu

### ISSUE THREAD

**Issue by naitiksoni92** [michaldrabik/TapBarMenu#16]
Can you please guide, I want to use in fragment (support.v4.app)

Here is the full error Log--
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.valueshipr.cargo.qa, PID: 32461
    java.lang.NullPointerException: Attempt to read from null array
        at com.michaldrabik.tapbarmenulib.TapBarMenu.onDraw(TapBarMenu.java:349)
        at android.view.View.draw(View.java:17083)
        at android.view.View.updateDisplayListIfDirty(View.java:16065)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.draw(View.java:17086)
        at android.view.View.updateDisplayListIfDirty(View.java:16065)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.draw(View.java:17086)
        at android.view.View.updateDisplayListIfDirty(View.java:16065)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.updateDisplayListIfDirty(View.java:16060)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.draw(View.java:17086)
        at android.view.View.updateDisplayListIfDirty(View.java:16065)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.updateDisplayListIfDirty(View.java:16060)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.updateDisplayListIfDirty(View.java:16060)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.updateDisplayListIfDirty(View.java:16060)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.updateDisplayListIfDirty(View.java:16060)
        at android.view.View.draw(View.java:16849)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
        at android.view.View.draw(View.java:17086)
        at com.android.internal.policy.DecorView.draw(DecorView.java:751)
        at android.view.View.updateDisplayListIfDirty(View.java:16065)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2808)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2616)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2223)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by michaldrabik** [comment]
I can take a look. Can you share a sample app with this issue happening?
